### ISSUE TITLE
Don't encode to utf-8 parsing input

### ISSUE THREAD

**Issue by mondeja** [dominickpastore/pymd4c#29]
> Previously reported here: https://github.com/mondeja/mdpo/issues/150

### Minimal reproducible example

<details>
  <summary>Input</summary>

```python
import md4c

def enter_block_callback(block, details):
    print("ENTER BLOCK", block, details)

def leave_block_callback(block, details):
    print("LEAVE BLOCK", block, details)

def enter_span_callback(block, details):
    print("ENTER SPAN", block, details)

def leave_span_callback(block, details):
    print("LEAVE SPAN", block, details)

def text_callback(block, text):
    print("TEXT", text)

content = '''
\udc93
foo
'''
parser = md4c.GenericParser(0)
parser.parse(content,
             enter_block_callback,
             leave_block_callback,
             enter_span_callback,
             leave_span_callback,
             text_callback)
```

</details>

<details>
  <summary>Error</summary>

```
Traceback (most recent call last):
  File "foo.py", line N, in <module>
    parser.parse(content,
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc93' in position 1: surrogates not allowed
```

</details>

### Possible cause

It seems that `s#` converts text to C string using `utf-8` encoding, which could not be desired. I'm not sure what of the [String and Buffers](https://docs.python.org/3/c-api/arg.html#strings-and-buffers) option should be used instead if it is the cause.

**Comment by dominickpastore** [comment]
This is an interesting issue. It isn't really PyMD4C's fault that it's failing on this input. Even plain old `print` gives the same error:

``` Python
>>> content = '''
... \udc93
... foo
... '''
>>> print(content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc93' in position 1: surrogates not allowed
```

CommonMark says that any sequence of codepoints is a valid Markdown document, but practically speaking, we need a UTF-8 byte stream to send to MD4C, and [the Unicode specification is adamant that it can't be done](http://unicode.org/faq/utf_bom.html#utf8-5).

That being said, we can force the encoding regardless, and the `s#` conversion will accept the bytes object we get from doing so. MD4C happily processes this input, but we get a new error when PyMD4C tries to create a Python string for the text callback:

``` Python
>>> content_bytes = content.encode('utf-8', 'surrogatepass')
>>> content_bytes
b'\n\xed\xb2\x93\nfoo\n'
>>> parser.parse(content_bytes,
...              enter_block_callback,
...              leave_block_callback,
...              enter_span_callback,
...              leave_span_callback,
...              text_callback)
ENTER BLOCK BlockType.DOC {}
ENTER BLOCK BlockType.P {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
```

I think the solution to this is probably to pass `bytes` objects to the callback when a `bytes` object is passed in. I need to figure out how to do this and make sure it won't break any of the rest of the code built on top of `GenericParser`.

**Comment by dominickpastore** [comment]
Ok, I'm in the middle of the fix, but it's turned out to be more involved than I expected. Should be ready later tonight, though.

What I've done is if the Markdown input is a `bytes` object:

- `HTMLRenderer.parse()` will return a `bytes`
- The text callback for `GenericParser` (and `ParserObject`) will get a `bytes` object as the text parameter
- Any [attribute lists](https://pymd4c.dcpx.org/pure_parsing.html#attributes) in the details dict for any other callback will have `bytes` objects
- Any single-character strings in a details dict (unordered list mark, ordered list delimiter, task list mark, fence char for code blocks) will still be of type `str`

I'm not 100% sure if that last one is the right decision or if I should make them single-element `bytes` also.

**Comment by mondeja** [comment]
Thank you for the fix 👍🏼 

I'm wondering now how I should properly parse a text with utf-16 characters? Using `text.encode('utf-8', 'surrogatepass')` passing it to `GenericParser.parse`?

**Comment by dominickpastore** [comment]
When you say "with utf-16 characters," you just mean text like the example above, with surrogate characters, right? The real problem is that such text is malformed, and it will give you problems with a lot of Python functions. I think it's not unreasonable to reject it with an error.

If you want to force it to work, encoding it with `text.encode('utf-8', 'surrogatepass')` before parsing will succeed now. But it does mean that the output will be `bytes` as a result, which I suspect you'll probably need to convert back to `str` with `output.decode('utf-8', 'surrogatepass')`. To me, it feels like a lot of extra code complexity for what is technically invalid input, but the decision is yours.

One other option would be to use `bytes` the whole way through. For example, if reading from a file, do `open(input_file, 'rb')`, then the data you read will be `bytes` from the beginning. But that might end up causing other problems, such as the lack of [universal newlines](https://docs.python.org/3/library/functions.html#open-newline-parameter).

**Comment by mondeja** [comment]
Thanks for the explanation @dominickpastore
