### ISSUE TITLE
Install fails with `pip<19.3`

### ISSUE THREAD

**Issue by mondeja** [dominickpastore/pymd4c#31]
Install `pip==19.2.3` in a virtual environment and execute `python3 -m pip install --no-cache-dir pymd4c` inside it to reproduce this.

Previously reported in https://github.com/mondeja/mdpo/issues/180, but I'm reproducing the error with later versions of Python.

I'm getting locally the next traceback:

<details>
<summary>Traceback</summary>

```
Collecting pymd4c
  Downloading https://files.pythonhosted.org/packages/ae/7c/154eea1a02c6340d14e919a3d803c9e268e3cc7d3a00821a362b071c9319/pymd4c-1.1.1.tar.gz
Building wheels for collected packages: pymd4c
  Building wheel for pymd4c (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /.../pymd4c/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ffyy4c0/pymd4c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ffyy4c0/pymd4c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h_vyvml0 --python-tag cp36
       cwd: /tmp/pip-install-2ffyy4c0/pymd4c/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/md4c
  copying md4c/enums.py -> build/lib.linux-x86_64-3.6/md4c
  copying md4c/parser.py -> build/lib.linux-x86_64-3.6/md4c
  copying md4c/__init__.py -> build/lib.linux-x86_64-3.6/md4c
  creating build/lib.linux-x86_64-3.6/md4c/domparser
  copying md4c/domparser/ast.py -> build/lib.linux-x86_64-3.6/md4c/domparser
  copying md4c/domparser/domparser.py -> build/lib.linux-x86_64-3.6/md4c/domparser
  copying md4c/domparser/__init__.py -> build/lib.linux-x86_64-3.6/md4c/domparser
  running egg_info
  writing pymd4c.egg-info/PKG-INFO
  writing dependency_links to pymd4c.egg-info/dependency_links.txt
  writing requirements to pymd4c.egg-info/requires.txt
  writing top-level names to pymd4c.egg-info/top_level.txt
  reading manifest file 'pymd4c.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pymd4c.egg-info/SOURCES.txt'
  running build_ext
  building 'md4c._md4c' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc -I/usr/local/include -I/.../pymd4c/venv/include -I/opt/python/python3.6/include/python3.6m -c src/pymd4c.c -o build/temp.linux-x86_64-3.6/src/pymd4c.o
  src/pymd4c.c:37:10: fatal error: pymd4c.h: No existe el archivo o el directorio
     37 | #include "pymd4c.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pymd4c
  Running setup.py clean for pymd4c
Failed to build pymd4c
Installing collected packages: pymd4c
  Running setup.py install for pymd4c ... error
    ERROR: Command errored out with exit status 1:
     command: /.../pymd4c/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ffyy4c0/pymd4c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ffyy4c0/pymd4c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lej0c46y/install-record.txt --single-version-externally-managed --compile --install-headers /.../pymd4c/venv/include/site/python3.6/pymd4c
         cwd: /tmp/pip-install-2ffyy4c0/pymd4c/
    Complete output (31 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/md4c
    copying md4c/enums.py -> build/lib.linux-x86_64-3.6/md4c
    copying md4c/parser.py -> build/lib.linux-x86_64-3.6/md4c
    copying md4c/__init__.py -> build/lib.linux-x86_64-3.6/md4c
    creating build/lib.linux-x86_64-3.6/md4c/domparser
    copying md4c/domparser/ast.py -> build/lib.linux-x86_64-3.6/md4c/domparser
    copying md4c/domparser/domparser.py -> build/lib.linux-x86_64-3.6/md4c/domparser
    copying md4c/domparser/__init__.py -> build/lib.linux-x86_64-3.6/md4c/domparser
    running egg_info
    writing pymd4c.egg-info/PKG-INFO
    writing dependency_links to pymd4c.egg-info/dependency_links.txt
    writing requirements to pymd4c.egg-info/requires.txt
    writing top-level names to pymd4c.egg-info/top_level.txt
    reading manifest file 'pymd4c.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pymd4c.egg-info/SOURCES.txt'
    running build_ext
    building 'md4c._md4c' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc -I/usr/local/include -I/.../pymd4c/venv/include -I/opt/python/python3.6/include/python3.6m -c src/pymd4c.c -o build/temp.linux-x86_64-3.6/src/pymd4c.o
    src/pymd4c.c:37:10: fatal error: pymd4c.h: No existe el archivo o el directorio
       37 | #include "pymd4c.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /.../pymd4c/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ffyy4c0/pymd4c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ffyy4c0/pymd4c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lej0c46y/install-record.txt --single-version-externally-managed --compile --install-headers /.../pymd4c/venv/include/site/python3.6/pymd4c Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

</details>

It seems that `19.3` is the first pip version that support wheels. Should be added `pip>=19.3` to `install_requires` in `setup.py` or should I declare in documentation the minimum required version of PIP to install without manually compile `md4c`?

**Comment by dominickpastore** [comment]
Ah. So the problem isn't wheels in general. There are two things going on here.

1. Pip version 19.3 was the first to support the manylinux2014\* tag. This is the platform I'm building the Linux packages on. Since older versions of pip don't recognize this platform (including the version that comes with Python 3.6, unfortunately), those versions attempt to build from the source package when on Linux.

   While that would be slower, theoretically it should still work, except for two things. First, the user would need development headers for Python and MD4C installed (and they may have the former, but they almost certainly don't have the latter). Second, there's problem (2) below, which is what's causing the error in your traceback.

2.  For some reason, in some situations (and I'm not entirely sure which situations these are yet), Python isn't finding the header files in `<repository>/src/`. This is where the `"pymd4c.h"` header is. I first saw this when using the new `python3 -m build` tool recently, but it doesn't happen when building wheels with `pip wheel`, so I didn't worry about it.

I do need to look into what's causing (2) and fix it (probably something in setup.py), but I don't think that alone would fix the problem for Linux users with an old version of pip. A build from source will still require the MD4C C library, which users are unlikely to have installed.

The best solution for these users is to upgrade pip (after all, pip itself warns you when you're using an old version). But to avoid forcing that, I can go ahead and add manylinux1 builds for 3.6.

**Two words of caution:**

1) I wasn't necessarily planning on supporting Python 3.6 at all once it stops receiving security updates at the end of this year. Let me know if you think that's a problem.
2) I can't provide 32-bit or ARM packages currently, because GitHub Actions doesn't provide those platforms. Pip on those architectures (including M1 Macs) will always have to build from the source package.

---

*\*I'm not sure if you are familiar with manylinux, but if not, some background: Linux has a complicated relationship with pre-built binary packages (of any sort). Unlike Windows and Mac, different Linux distros come with different versions of libraries in their base install. For Python, this is mainly a concern for packages with C extensions, since they need to be compiled against these libraries. Python's solution is manylinux, a sort of "lowest common denominator" Linux platform. The idea is you pick a handful of core libraries that are so common that every distro will have them. Then, you build on as old a distro as possible, so you get old versions of these libraries, backward compatible with any newer versions. Finally, after building, any required libraries that aren't in the core set (e.g. MD4C in this case) are included inside the wheel.*

*Manylinux1 was the first incarnation of this concept, and it used CentOS 5, the oldest common distro available at the time. But eventually, CentOS 5 reached end-of-life, so a new version, manylinux2010, was announced using CentOS 6. CentOS 6 is now EOL as well, so we're on manylinux2014, using CentOS 7.*

**Comment by mondeja** [comment]
> I can go ahead and add manylinux1 builds for 3.6.

> I wasn't necessarily planning on supporting Python 3.6 at all once it stops receiving security updates at the end of this year. Let me know if you think that's a problem.

Don't worry about that, I'm going to drop Python3.6 support as well in the next year anyways, when will do it will depend on how fast the overall Python ecosystem upgrades removing support for this version.

It feels that the best would be just to recommend the PIP update if someone complains about this problem.

> I can't provide 32-bit or ARM packages currently, because GitHub Actions doesn't provide those platforms. Pip on those architectures (including M1 Macs) will always have to build from the source package.

Is not a big problem I guess, I'll just update the installation recommendations for these architectures a bit.

> Manylinux1 was the first incarnation of this concept, and it used CentOS 5, the oldest common distro available at the time. But eventually, CentOS 5 reached end-of-life, so a new version, manylinux2010, was announced using CentOS 6. CentOS 6 is now EOL as well, so we're on manylinux2014, using CentOS 7.

Wow, thank you for this part of the explanation, I didn't know how manylinux started! 🙏🏼

Closing this for now, but feel free to reuse this issue changing the name for tracking 2) problem if you feel that this discussion provides some useful context. Cheers!

**Comment by dominickpastore** [comment]
I went ahead and added a manylinux1 build to the GitHub Actions workflow. As for the future of 3.6 support: I don't really have much reason to *purposefully* remove support for 3.6 once it reaches EOL. The builds and tests are automated, and I don't currently miss any features from 3.7, so it's not any extra effort to keep it. But if it later becomes inconvenient for some reason, I won't feel bad about dropping it.

For problem 2, turns out Python doesn't package header files when you build a source distribution, and the only way to include them is to add them to MANIFEST.in. I'm surprised. (Related: https://github.com/pypa/setuptools/issues/1162) My own builds and the GitHub Actions builds worked because they are all building directly from the repository, where the headers are already present.

All of this is fixed now. I'll be pushing and making a release (1.1.2) in a few minutes.

**Comment by dominickpastore** [comment]
Turns out manylinux1 is incompatible with GitHub Actions, so I couldn't publish a build for that platform after all. Oh well. I added some FAQ entries to the docs about unexpected builds from source instead. The release is out now.
