### ISSUE TITLE
Latest MacOS wheels

### ISSUE THREAD

**Issue by mondeja** [dominickpastore/pymd4c#33]
Hi again.

It seems that the current wheels for MacOS don't work, at least on Github Actions. I've created a repository to show the problem comparing the installation of pymd4c against pylance on all MacOS and Python versions supported by GHA, you can [see the execution here](https://github.com/mondeja/pymd4c-macos-test/actions/runs/3675194995). Used pylance because it depends on other wheels as well (pandas, pillow, numpy...).

As you're using Github Actions to build wheels, I guess that they should work standalone, but is not the case. I would like to suggest you to use [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) to build them, they are supporting macOS Apple Silicon now.

**Comment by dominickpastore** [comment]
Alright, this turned out to be pretty tricky, but I just pushed a couple new commits to master that should do it. (Just a heads up: I normally avoid force push, but I did do a force push this time. Only commits since the last release got overwritten.)

I'm about to push a new release tag that should kick off the build. It takes quite a bit longer now that it's building many more packages, so I'm not going to stay awake while it runs tonight. But it should hopefully succeed, and if it does, please do let me know if the new packages work for you. I don't have a Mac to test them with, unfortunately.

**Comment by mondeja** [comment]
It works awesome. Glad to see that now pymd4c offer wheels for so many architectures, good work and thank you 👍🏼
